# Generated by Django 6.0.6 on 2026-06-09 17:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpinnerSpin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("spun_at", models.DateTimeField(auto_now_add=True)),
                ("spin_date", models.DateField()),
            ],
            options={
                "db_table": "spinner_spins",
                "ordering": ["-spun_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="loyaltytransaction",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="gamingitem",
            name="capacity",
        ),
        migrations.AddField(
            model_name="booking",
            name="is_happy_hour",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                help_text="Generated QR code image for this booking",
                null=True,
                upload_to="booking_qr/",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="qr_token",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique token embedded in the booking QR code",
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="event_booking_qr/"
            ),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=1, help_text="Maximum number of people allowed per booking"
            ),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="min_capacity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Minimum number of people required to book (used for OTT/Streaming)",
            ),
        ),
        migrations.AddField(
            model_name="loyaltytransaction",
            name="granted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin user who granted these points (ADMIN_GRANT only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="granted_loyalty_transactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="spinnerreward",
            name="happy_hour_duration",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Duration of free play in hours (used when reward_type=HAPPY_HOUR)",
            ),
        ),
        migrations.AddField(
            model_name="spinnerreward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("points", "Loyalty Points"),
                    ("happy_hour", "Happy Playing Hour"),
                    ("coupon", "Coupon / Discount"),
                ],
                default="points",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="combo_pack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bookings",
                to="gaming.combopack",
            ),
        ),
        migrations.AlterField(
            model_name="combopack",
            name="loyalty_bonus",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Extra loyalty points awarded when this combo is booked",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("ps5", "PS5"),
                    ("pool", "Pool"),
                    ("ott", "OTT / Streaming"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="loyaltytransaction",
            name="booking",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="loyalty_transactions",
                to="gaming.booking",
            ),
        ),
        migrations.AlterField(
            model_name="loyaltytransaction",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("earned", "Earned (Booking Completed)"),
                    ("redeemed", "Redeemed"),
                    ("admin_grant", "Admin Grant"),
                    ("spinner", "Spinner Win"),
                    ("combo_bonus", "Combo Pack Bonus"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="expiry_days",
            field=models.PositiveIntegerField(
                default=30, help_text="How many days before a won reward expires"
            ),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="probability",
            field=models.PositiveIntegerField(
                help_text="Spinner weight — higher value = more likely to land"
            ),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="reward_points",
            field=models.PositiveIntegerField(
                default=0, help_text="Points awarded (used when reward_type=POINTS)"
            ),
        ),
        migrations.CreateModel(
            name="BookingExportRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "period_type",
                    models.CharField(
                        choices=[
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("yearly", "Yearly"),
                            ("custom", "Custom Range"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "custom_start",
                    models.DateField(
                        blank=True,
                        help_text="Required when period_type=CUSTOM",
                        null=True,
                    ),
                ),
                (
                    "custom_end",
                    models.DateField(
                        blank=True,
                        help_text="Required when period_type=CUSTOM",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        help_text="Generated Excel file — populated by background task",
                        null=True,
                        upload_to="booking_exports/",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Populated if the export task fails"
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="export_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "booking_export_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BookingMember",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "name",
                    models.CharField(
                        help_text="Full name of the member", max_length=150
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="Optional contact number for the member",
                        max_length=20,
                    ),
                ),
                (
                    "is_admin_added",
                    models.BooleanField(
                        default=False,
                        help_text="True when an admin added this member (extra guest)",
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="gaming.booking",
                    ),
                ),
            ],
            options={
                "db_table": "booking_members",
            },
        ),
        migrations.CreateModel(
            name="HappyHourSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "allocated_date",
                    models.DateField(
                        help_text="Weekday (Mon–Fri) when the free play is scheduled"
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "is_used",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True once the user redeems this slot",
                    ),
                ),
                (
                    "expires_at",
                    models.DateField(
                        help_text="The slot expires and can no longer be booked after this date"
                    ),
                ),
                (
                    "gaming_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank until admin allocates a specific item",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="happy_hour_slots",
                        to="gaming.gamingitem",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="happy_hour_slots",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "happy_hour_slots",
                "ordering": ["allocated_date", "start_time"],
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="happy_hour_slot",
            field=models.OneToOneField(
                blank=True,
                help_text="The spinner-awarded slot that created this booking, if any",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="booking",
                to="gaming.happyhourslot",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["qr_token"], name="bookings_qr_toke_55cb43_idx"),
        ),
        migrations.AddField(
            model_name="spinnerspin",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="spins",
                to="gaming.spinnerreward",
            ),
        ),
        migrations.AddField(
            model_name="spinnerspin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spinner_spins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="happyhourslot",
            name="spinner_spin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="happy_hour_slots",
                to="gaming.spinnerspin",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="spinnerspin",
            unique_together={("user", "spin_date")},
        ),
    ]
