# Generated by Django 6.0.6 on 2026-06-20 18:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0003_userdevice"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdevice",
            name="device_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("desktop", "Desktop"),
                    ("mobile", "Mobile"),
                    ("tablet", "Tablet"),
                    ("bot", "Bot"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userdevice",
            name="logged_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="browser",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="device_name",
            field=models.CharField(default="Unknown", max_length=255),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="is_online",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="last_seen",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="login_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="operating_system",
            field=models.CharField(default="Unknown", max_length=150),
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_online", "-last_seen"],
                name="user_device_user_id_c1626c_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="userdevice",
            constraint=models.UniqueConstraint(
                fields=("user", "device_id"), name="unique_user_device"
            ),
        ),
    ]
