# Generated by Django 6.0.6 on 2026-06-20 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0004_userdevice_device_id_userdevice_device_type_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="userdevice",
            new_name="device_user_status_seen_idx",
            old_name="user_device_user_id_c1626c_idx",
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="last_seen",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="userdevice",
            name="login_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
