# Generated by Django 6.0.6 on 2026-06-22 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "gaming",
            "0005_rename_user_device_user_id_c1626c_idx_device_user_status_seen_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventbooking",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="amount_paid",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="approved_event_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="booking_id",
            field=models.CharField(
                default=0, editable=False, max_length=30, unique=True
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="checked_in",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="email",
            field=models.EmailField(default=0, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="full_name",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="phone",
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("attended", "Attended"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
