# Generated by Django 6.0.6 on 2026-06-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0006_alter_eventbooking_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventbooking",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="full_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
