# Generated by Django 6.0.6 on 2026-06-23 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0008_booking_approved_at_booking_approved_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="gaming.gamingitem",
            ),
        ),
    ]
