# Generated by Django 6.0.6 on 2026-06-23 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0009_alter_booking_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="HappyHourTemplateSlot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "weekday",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                        ]
                    ),
                ),
                ("slot_name", models.CharField(max_length=100)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "happy_hour_template_slots",
            },
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("ps5", "PS5"),
                    ("pool", "Pool"),
                    ("vr", "VR"),
                    ("simulator", "Simulator"),
                    ("multiplayer_games", "Multiplayer Games"),
                    ("board_games", "Board Games"),
                    ("card_games", "Card Games"),
                    ("ott", "OTT / Streaming"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
    ]
