# Generated by Django 6.0.6 on 2026-06-23 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0010_happyhourtemplateslot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("booking_loyalty_points", models.PositiveIntegerField(default=5)),
                ("spinner_points_reward", models.PositiveIntegerField(default=10)),
            ],
            options={
                "db_table": "app_settings",
            },
        ),
        migrations.AlterModelOptions(
            name="happyhourslot",
            options={},
        ),
        migrations.AlterModelOptions(
            name="happyhourtemplateslot",
            options={"ordering": ["weekday", "display_order"]},
        ),
        migrations.RemoveField(
            model_name="spinnerreward",
            name="coupon_code",
        ),
        migrations.RemoveField(
            model_name="spinnerreward",
            name="expiry_days",
        ),
        migrations.RemoveField(
            model_name="spinnerreward",
            name="happy_hour_duration",
        ),
        migrations.AddField(
            model_name="happyhourslot",
            name="allow_user_to_choose_game",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="happyhourslot",
            name="redeemed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="happyhourslot",
            name="template_slot",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocated_slots",
                to="gaming.happyhourtemplateslot",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="happyhourtemplateslot",
            name="display_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="happyhourtemplateslot",
            name="probability",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name="spinnerreward",
            name="template_slot",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spinner_rewards",
                to="gaming.happyhourtemplateslot",
            ),
        ),
        migrations.AddField(
            model_name="spinnerspin",
            name="spin_week",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spinnerspin",
            name="spin_year",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="spinnerspin",
            unique_together={("user", "spin_week", "spin_year")},
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="allocated_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="expires_at",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="gaming_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="happy_hour_slots",
                to="gaming.gamingitem",
            ),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="is_used",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="probability",
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="reward_points",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="spinnerreward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("happy_hour", "Happy Hour"),
                    ("points", "Points"),
                    ("lose", "Better Luck Next Time"),
                ],
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="HappyHourBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="happy_hour_bookings",
                        to="gaming.booking",
                    ),
                ),
                (
                    "happy_hour_slot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="happy_booking",
                        to="gaming.happyhourslot",
                    ),
                ),
            ],
            options={
                "db_table": "happy_hour_bookings",
            },
        ),
        migrations.RemoveField(
            model_name="spinnerspin",
            name="spin_date",
        ),
    ]
