# Generated by Django 6.0.6 on 2026-06-23 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0011_appsetting_alter_happyhourslot_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="happy_hour_booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="redeemed_booking",
                to="gaming.happyhourbooking",
            ),
        ),
    ]
