# Generated by Django 6.0.6 on 2026-06-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0012_booking_happy_hour_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spinnerreward",
            name="reward_type",
            field=models.CharField(
                choices=[
                    ("happy_hour", "Happy Hour"),
                    ("points", "Points"),
                    ("better_luck", "Better Luck Next Time"),
                ],
                max_length=20,
            ),
        ),
    ]
