# Generated by Django 6.0.6 on 2026-08-01 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0015_booking_cancellation_reason_booking_cancelled_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsAndConditions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('version', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'terms_and_conditions',
            },
        ),
    ]
