# Generated by Django 6.0.6 on 2026-08-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0016_termsandconditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_users', to='gaming.termsandconditions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
