# Generated by Django 6.0.6 on 2026-08-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0017_customuser_accepted_terms_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="termsandconditions",
            options={"ordering": ["-effective_date"]},
        ),
        migrations.AddField(
            model_name="termsandconditions",
            name="is_current",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name="termsandconditions",
            table="terms_conditions",
        ),
    ]
