# Generated by Django 6.0.6 on 2026-08-15 09:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0018_alter_termsandconditions_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamingitem",
            name="max_capacity",
            field=models.PositiveIntegerField(
                default=14, help_text="Maximum number of people allowed per booking"
            ),
        ),
        migrations.CreateModel(
            name="HappyHourAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "offer_percentage",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Discount percentage offered during this slot",
                    ),
                ),
                (
                    "loyalty_points",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Loyalty points awarded for using this slot",
                    ),
                ),
                (
                    "is_free",
                    models.BooleanField(
                        default=False, help_text="Whether the slot is completely free"
                    ),
                ),
                (
                    "max_bookings",
                    models.PositiveIntegerField(
                        default=1, help_text="Maximum number of bookings allowed"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "db_table": "happy_hour_allocations",
                "ordering": ["date", "start_time"],
                "indexes": [
                    models.Index(fields=["date"], name="happy_hour__date_0edb04_idx"),
                    models.Index(
                        fields=["date", "start_time"],
                        name="happy_hour__date_1aa79c_idx",
                    ),
                    models.Index(
                        fields=["is_active"], name="happy_hour__is_acti_9565a6_idx"
                    ),
                ],
            },
        ),
    ]
