# Generated by Django 6.0.6 on 2026-08-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0019_alter_gamingitem_max_capacity_happyhourallocation"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="userdevice",
            name="device_user_status_seen_idx",
        ),
        migrations.AddIndex(
            model_name="userdevice",
            index=models.Index(
                fields=["user", "is_deleted", "is_online", "-last_seen"],
                name="device_user_active_seen_idx",
            ),
        ),
    ]
