# Generated by Django 6.0.6 on 2026-09-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0020_remove_userdevice_device_user_status_seen_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="combopack",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="combopack",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exclusiveevent",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exclusiveevent",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamecategory",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamecategory",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="combopack",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exclusiveevent",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
