# Generated by Django 6.0.6 on 2026-09-20 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0021_combopack_image_content_type_combopack_image_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="qr_code_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
