# Generated by Django 6.0.6 on 2026-09-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0022_booking_qr_code_content_type_booking_qr_code_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="qr_code_content_type",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="qr_code_name",
        ),
        migrations.RemoveField(
            model_name="combopack",
            name="image_content_type",
        ),
        migrations.RemoveField(
            model_name="combopack",
            name="image_name",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image_content_type",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile_image_name",
        ),
        migrations.RemoveField(
            model_name="eventbooking",
            name="qr_code_content_type",
        ),
        migrations.RemoveField(
            model_name="eventbooking",
            name="qr_code_name",
        ),
        migrations.RemoveField(
            model_name="exclusiveevent",
            name="image_content_type",
        ),
        migrations.RemoveField(
            model_name="exclusiveevent",
            name="image_name",
        ),
        migrations.RemoveField(
            model_name="gamecategory",
            name="image_content_type",
        ),
        migrations.RemoveField(
            model_name="gamecategory",
            name="image_name",
        ),
        migrations.RemoveField(
            model_name="gamingitem",
            name="image_content_type",
        ),
        migrations.RemoveField(
            model_name="gamingitem",
            name="image_name",
        ),
        migrations.AlterField(
            model_name="booking",
            name="qr_code",
            field=models.ImageField(blank=True, null=True, upload_to="booking_qr/"),
        ),
        migrations.AlterField(
            model_name="combopack",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="combo_packs/"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.ImageField(blank=True, null=True, upload_to="users/profile/"),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to="event_booking_qr/"
            ),
        ),
        migrations.AlterField(
            model_name="exclusiveevent",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="events/"),
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="game_categories/"
            ),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="gaming_items/"),
        ),
    ]
