# Generated by Django 6.0.6 on 2026-09-20 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0024_alter_booking_user_alter_eventbooking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="qr_code_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="qr_code_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="combopack",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="combopack",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile_image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="eventbooking",
            name="qr_code_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="exclusiveevent",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="exclusiveevent",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamecategory",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamecategory",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="image_content_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="gamingitem",
            name="image_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="booking",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="gaming.gamingitem",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="combopack",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="accepted_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_users",
                to="gaming.termsandconditions",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="event_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="exclusiveevent",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gaming_items",
                to="gaming.gamecategory",
            ),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="gaming_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="happy_hour_slots",
                to="gaming.gamingitem",
            ),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="template_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_slots",
                to="gaming.happyhourtemplateslot",
            ),
        ),
        migrations.AlterField(
            model_name="spinnerspin",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spins",
                to="gaming.spinnerreward",
            ),
        ),
    ]
