# Generated by Django 6.0.6 on 2026-09-20 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0026_remove_booking_qr_code_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="gaming.gamingitem",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="accepted_terms",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accepted_users",
                to="gaming.termsandconditions",
            ),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gaming_items",
                to="gaming.gamecategory",
            ),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="gaming_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="happy_hour_slots",
                to="gaming.gamingitem",
            ),
        ),
        migrations.AlterField(
            model_name="happyhourslot",
            name="template_slot",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocated_slots",
                to="gaming.happyhourtemplateslot",
            ),
        ),
        migrations.AlterField(
            model_name="spinnerspin",
            name="reward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="spins",
                to="gaming.spinnerreward",
            ),
        ),
    ]
