# Generated by Django 6.0.6 on 2026-09-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gaming", "0027_alter_booking_item_alter_customuser_accepted_terms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="combopack",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile_image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="eventbooking",
            name="qr_code",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="exclusiveevent",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamecategory",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="gamingitem",
            name="image",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
