# Generated by Django 6.0.6 on 2026-10-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gaming', '0028_alter_booking_qr_code_alter_combopack_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetotp',
            name='otp',
            field=models.CharField(max_length=128),
        ),
    ]
